server:
  port: 8085
spring:
  application:
    name: springboot-minio
minio:
  endpoint: http://服务器IP地址:9000
  port: 9000
  accessKey: 密钥
  secretKey: 密钥
  secure: false
  bucket-name: commons
  image-size: 10485760
  file-size: 1073741824
