server:
  port: 8085
spring:
  application:
    name: springboot-minio
minio:
  endpoint: http://wxhlxb.icu:9000
  port: 9000
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  secure: false
  bucket-name: commons
  image-size: 10485760
  file-size: 1073741824
