spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/vueadmin?serverTimezone=GMT&userSSL=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 8889